USE [master]
GO

/****** Object:  Database [Drugstores]    Script Date: 8/19/2022 4:38:48 PM ******/
CREATE DATABASE [Drugstores]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Drugstores', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Drugstores.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Drugstores_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Drugstores_log.ldf' , SIZE = 2048KB , MAXSIZE = 10240KB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Drugstores].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Drugstores] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Drugstores] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Drugstores] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Drugstores] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Drugstores] SET ARITHABORT OFF 
GO

ALTER DATABASE [Drugstores] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Drugstores] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Drugstores] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Drugstores] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Drugstores] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Drugstores] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Drugstores] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Drugstores] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Drugstores] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Drugstores] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Drugstores] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Drugstores] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Drugstores] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Drugstores] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Drugstores] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Drugstores] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Drugstores] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Drugstores] SET RECOVERY FULL 
GO

ALTER DATABASE [Drugstores] SET  MULTI_USER 
GO

ALTER DATABASE [Drugstores] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Drugstores] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Drugstores] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Drugstores] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Drugstores] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Drugstores] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Drugstores] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Drugstores] SET  READ_WRITE 
GO

USE [Drugstores]
GO

/****** Object:  Table [dbo].[Drugstores]    Script Date: 8/26/2022 10:18:10 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Drugstores](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Address] [nvarchar](50) NULL,
	[Phone] [nvarchar](20) NULL,
 CONSTRAINT [PK_Drugstores] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Goods](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Goods] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Warehouses](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[DrugstoreId] [int] NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Warehouses] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Warehouses]  WITH CHECK ADD  CONSTRAINT [FK_Warehouses_Drugstores] FOREIGN KEY([DrugstoreId])
REFERENCES [dbo].[Drugstores] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[Warehouses] CHECK CONSTRAINT [FK_Warehouses_Drugstores]
GO

CREATE TABLE [dbo].[Parties](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[GoodsId] [int] NOT NULL,
	[WarehouseId] [int] NOT NULL,
	[Count] [int] NOT NULL,
 CONSTRAINT [PK_Parties] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Parties]  WITH CHECK ADD  CONSTRAINT [FK_Parties_Goods] FOREIGN KEY([GoodsId])
REFERENCES [dbo].[Goods] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[Parties] CHECK CONSTRAINT [FK_Parties_Goods]
GO

ALTER TABLE [dbo].[Parties]  WITH CHECK ADD  CONSTRAINT [FK_Parties_Warehouses] FOREIGN KEY([WarehouseId])
REFERENCES [dbo].[Warehouses] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[Parties] CHECK CONSTRAINT [FK_Parties_Warehouses]
GO

